#List of all jobs supported by ATP
from atp.models import Job
import global_constants as const
from atp import constants as atp_const
from shared.constant_dict import ConstantDict
job_list = ConstantDict({
    1 : Job((1, "executor.ping", 60 * 60 * 24, atp_const.JOB_ETA_TYPE_NEVER, {"delay": 0})),
    # digest_email by default is regenerate = None and unread = None. See job 78 for regenerate = True case. The unread = True was for testing only and not run
    2 : Job((2, "digest.tasks.digest_email", 86400, atp_const.JOB_ETA_TYPE_PREVIOUS_ETA, {"profile": 0})),
    3 : Job((3, "digest.tasks.digest_checkins", 3600, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0})),
    4 : Job((4, "digest.tasks.digest_update", 12 * 60 * 60, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"list": 0})),
    5 : Job((5, "digest.tasks.digest_update", 12 * 60 * 60, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0})),
    6 : Job((6, "digest.tasks.digest_update_daily_reports", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"name": "content_actions", "days": 3})),
    7 : Job((7, "digest.tasks.digest_update_daily_reports", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"name": "digest_opens", "days": 3})),
    8 : Job((8, "digest.tasks.digest_update_daily_reports", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"name": "digest_urls", "days": 7})),
    9 : Job((9, "digest.tasks.digest_update_daily_reports", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"name": "email_digests", "days": 7})),
    10 : Job((10, "digest.tasks.digest_update_daily_reports", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"name": "incremental_digests", "days": 7})),
    11 : Job((11, "digest.tasks.digest_update_daily_reports", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"name": "media_clicks", "days": 3})),
    12 : Job((12, "digest.tasks.digest_update_daily_reports", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"name": "url_quality", "days": 7})),
    13 : Job((13, "contacts.tasks.add_to_autoresponder", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"shard_id": 0}), all_users=True),
    14 : Job((14, "contacts.tasks.email_daily", 86400, atp_const.JOB_ETA_TYPE_PREVIOUS_ETA, {"profile": 0}), external_apis=[const.LINKEDIN, const.FACEBOOK, const.TRIPIT, const.GOOGLE_CALENDAR, const.OUTLOOK_EWS, const.OUTLOOK_CALENDAR, const.YAHOO_CALENDAR]),
    15 : Job((15, "contacts.tasks.send_engage_events", 86400, atp_const.JOB_ETA_TYPE_PREVIOUS_ETA, {"profile": 0})),
    16 : Job((16, "contacts.tasks.generate_trial_expiration_emails", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, None), all_users=True),
    17 : Job((17, "contacts.tasks.generate_reminders", 43200, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"shard_id": 0}), all_users=True),
    18 : Job((18, "contacts.tasks.refresh_network_stats", 604800, atp_const.JOB_ETA_TYPE_CURRENT_TIME, None), all_users=True),
    19 : Job((19, "contacts.tasks.sync_calendar_events", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.GOOGLE_CALENDAR}), throttleable=True, external_apis=[const.GOOGLE_CALENDAR]),
    20 : Job((20, "contacts.tasks.sync_calendar_events", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.OUTLOOK_CALENDAR}), throttleable=True, external_apis=[const.OUTLOOK_CALENDAR]),
    21 : Job((21, "contacts.tasks.sync_calls", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.GOOGLE_VOICE}), throttleable=True, external_apis=[const.GOOGLE_VOICE]),
    # One time executing jobs: Following jobs should be scheduled to execute once from staff page. The are never rescheduled.
    22 : Job((22, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.CARDMUNCH}), external_apis=[const.CARDMUNCH]),
    23 : Job((23, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.TWITTER_PUBLIC}), external_apis=[const.TWITTER_PUBLIC]),
    24 : Job((24, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.TWITTER}), external_apis=[const.TWITTER]),
    25 : Job((25, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.GOOGLE_CONTACTS}), external_apis=[const.GOOGLE_CONTACTS]),
    26 : Job((26, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.MAILCHIMP}), external_apis=[const.MAILCHIMP]),
    27 : Job((27, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.FACEBOOK_PUBLIC}), external_apis=[const.FACEBOOK_PUBLIC]),
    28 : Job((28, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.FACEBOOK}), external_apis=[const.FACEBOOK]),
    29 : Job((29, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.MAC_ADDRESS_BOOK_VCARD})),
    30 : Job((30, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.LINKEDIN_PUBLIC}), external_apis=[const.LINKEDIN_PUBLIC]),
    31 : Job((31, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.LINKEDIN}), external_apis=[const.LINKEDIN]),
    32 : Job((32, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.OUTLOOK_CONTACTS_CSV})),
    33 : Job((33, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.YAHOO_CONTACTS_CSV})),
    34 : Job((34, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.AWEBER}), external_apis=[const.AWEBER]),
    35 : Job((35, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.CONSTANT_CONTACT}), external_apis=[const.CONSTANT_CONTACT]),
    36 : Job((36, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.OUTLOOK_CONTACTS}), external_apis=[const.OUTLOOK_CONTACTS]),
    37 : Job((37, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.OUTLOOK_CONTACTS_MAC}), external_apis=[const.OUTLOOK_CONTACTS_MAC]),

    38 : Job((38, "contacts.tasks.sync_email_files", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0}), throttleable=True, external_apis=[const.EMAIL]),
    39 : Job((39, "contacts.tasks.sync_email_messages", 43200, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.EMAIL}), throttleable=True, external_apis=[const.EMAIL]),
    40 : Job((40, "contacts.tasks.sync_email_messages", 43200, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.OUTLOOK_MAIL}), throttleable=True, external_apis=[const.OUTLOOK_MAIL]),
    41 : Job((41, "contacts.tasks.sync_email_previews", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0}), throttleable=True, external_apis=[const.EMAIL]),
    42 : Job((42, "contacts.tasks.sync_facebook_birthdays", 604800, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0}), throttleable=True, external_apis=[const.FACEBOOK_BIRTHDAY_CALENDAR]),
    43 : Job((43, "contacts.tasks.merge_orphaned_contacts", 604800, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"shard_id": 0}), all_users=True),
    44 : Job((44, "contacts.tasks.sync_notes", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.EVERNOTE}), throttleable=True, external_apis=[const.EVERNOTE]),
    45 : Job((45, "contacts.tasks.profiles_from_email_links", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0}), external_apis=[const.FACEBOOK, const.FACEBOOK_PUBLIC, const.TWITTER, const.TWITTER_PUBLIC, const.LINKEDIN, const.LINKEDIN_PUBLIC, const.LINKEDIN_CSV]),
    46 : Job((46, "contacts.tasks.profiles_from_sites", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0}), external_apis=[const.FACEBOOK, const.FACEBOOK_PUBLIC, const.TWITTER, const.TWITTER_PUBLIC, const.LINKEDIN, const.LINKEDIN_PUBLIC, const.LINKEDIN_CSV]),
    47 : Job((47, "contacts.tasks.sync_contacts", 43200, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.EMAIL}), throttleable=True, external_apis=[const.EMAIL]),
    48 : Job((48, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.FACEBOOK_PUBLIC}), throttleable=True, external_apis=[const.FACEBOOK_PUBLIC]),
    49 : Job((49, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.FACEBOOK}), throttleable=True, external_apis=[const.FACEBOOK]),
    50 : Job((50, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.GOOGLE_CONTACTS}), throttleable=True, external_apis=[const.GOOGLE_CONTACTS]),
    51 : Job((51, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.LINKEDIN_PUBLIC}), throttleable=True, external_apis=[const.LINKEDIN_PUBLIC]),
    52 : Job((52, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.LINKEDIN}), throttleable=True, external_apis=[const.LINKEDIN]),
    53 : Job((53, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.TWITTER_PUBLIC}), throttleable=True, external_apis=[const.TWITTER_PUBLIC]),
    54 : Job((54, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.TWITTER}), throttleable=True, external_apis=[const.TWITTER]),
    55 : Job((55, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.AWEBER}), throttleable=True, external_apis=[const.AWEBER]),
    56 : Job((56, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.MAILCHIMP}), throttleable=True, external_apis=[const.MAILCHIMP]),
    57 : Job((57, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.CONSTANT_CONTACT}), throttleable=True, external_apis=[const.CONSTANT_CONTACT]),
    58 : Job((58, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.OUTLOOK_CONTACTS}), throttleable=True, external_apis=[const.OUTLOOK_CONTACTS]),
    59 : Job((59, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.LINKEDIN_CSV})),
    60 : Job((60, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_CONTACTS_MAC})),
    61 : Job((61, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_CONTACTS_CSV})),
    62 : Job((62, "contacts.tasks.sync_social_messages", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0}), throttleable=True, external_apis=[const.FACEBOOK, const.TWITTER, const.LINKEDIN]),
    63 : Job((63, "contacts.tasks.sync_social_messages", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.TWITTER}), throttleable=True, external_apis=[const.TWITTER]),
    64 : Job((64, "contacts.tasks.sync_social_messages", 86400, atp_const.JOB_ETA_TYPE_PREVIOUS_ETA, {"profile": 0, "service": const.FACEBOOK}), throttleable=True, external_apis=[const.FACEBOOK]),
    65 : Job((65, "contacts.tasks.sync_social_messages", 86400, atp_const.JOB_ETA_TYPE_PREVIOUS_ETA, {"profile": 0, "service": const.LINKEDIN}), throttleable=True, external_apis=[const.LINKEDIN]),
    66 : Job((66, "contacts.tasks.update_daily_reports", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"name": "daily_emails", "days": 7})),
    67 : Job((67, "contacts.tasks.delete_old_canceled_accounts", 7 * 24 * 60 * 60, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"shard_id": 0}), all_users=True),
    68 : Job((68, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.CARDMUNCH}), throttleable=True, external_apis=[const.CARDMUNCH]),

    # One time executing jobs: Following jobs should be scheduled to execute once from staff page. The are never rescheduled.
    69 : Job((69, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.LINKEDIN_CSV})),

    70 : Job((70, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.MAC_ADDRESS_BOOK_VCARD})),
    71 : Job((71, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.YAHOO_CONTACTS_CSV})),
    73 : Job((73, "digest.tasks.digest_purge", 7 * 24 * 60 * 60, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"shard_id": 0}), all_users=True),
    74 : Job((74, "contacts.tasks.profiles_from_email_addresses", 60 * 60, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"shard_id": 0}), all_users=True, external_apis=[const.LINKEDIN]),
    75 : Job((75, "contacts.tasks.delete_test_accounts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"shard_id": 0}), all_users=True),
    76 : Job((76, "contacts.tasks.sync_email_messages", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.EMAIL}), external_apis=[const.EMAIL]),
    77 : Job((77, "contacts.tasks.sync_email_messages", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.OUTLOOK_MAIL}), external_apis=[const.OUTLOOK_MAIL]),
    78 : Job((78, "digest.tasks.digest_email", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "regenerate" : "True"})),
    79 : Job((79, "contacts.tasks.sync_calendar_events", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.GOOGLE_CALENDAR, "full_calendar_scan": True}), external_apis=[const.GOOGLE_CALENDAR]),
    80 : Job((80, "contacts.tasks.sync_calendar_events", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_CALENDAR, "full_calendar_scan": True}), external_apis=[const.OUTLOOK_CALENDAR]),
    81 : Job((81, "executor.ping", 0, atp_const.JOB_ETA_TYPE_NEVER, {"delay": 0, "fail": "True"})),
    82 : Job((82, "contacts.tasks.email_daily", 86400, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "regenerate" : "True"})),

    83 : Job((83, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.EMAIL})),
    84 : Job((84, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.FACEBOOK})),
    85 : Job((85, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.GOOGLE_CONTACTS})),
    86 : Job((86, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.LINKEDIN})),
    87 : Job((87, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.TWITTER})),
    88 : Job((88, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_CALENDAR})),
    89 : Job((89, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_CONTACTS})),
    90 : Job((90, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_MAIL})),
    91 : Job((91, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.LINKEDIN_CSV})),
    92 : Job((92, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_CONTACTS_CSV})),
    93 : Job((93, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_CONTACTS})),
    94 : Job((94, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.CONSTANT_CONTACT})),
    95 : Job((95, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.AWEBER})),
    96 : Job((96, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.MAILCHIMP})),
    97 : Job((97, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.FACEBOOK_BIRTHDAY_CALENDAR})),
    98 : Job((98, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.GOOGLE_CALENDAR})),
    99 : Job((99, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.OUTLOOK_CONTACTS_MAC})),
    100 : Job((100, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.YAHOO_CONTACTS_CSV})),
    101 : Job((101, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.TWITTER_PUBLIC})),
    102 : Job((102, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.FACEBOOK_PUBLIC})),
    103 : Job((103, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.LINKEDIN_PUBLIC})),
    104 : Job((104, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.GOOGLE_VOICE})),
    105 : Job((105, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.CARDMUNCH})),
    106 : Job((106, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.EVERNOTE})),
    107 : Job((107, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.MAC_ADDRESS_BOOK_VCARD})),
    108 : Job((108, "contacts.tasks.delete_linkedin_contacts_account", 0, atp_const.JOB_ETA_TYPE_NEVER, {"linkedin_id": 0})),
    109 : Job((109, "contacts.tasks.sync_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.YAHOO_CONTACTS}), external_apis=[const.YAHOO_CONTACTS]),
    110 : Job((110, "contacts.tasks.sync_contacts", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.YAHOO_CONTACTS}), throttleable=True, external_apis=[const.YAHOO_CONTACTS]),
    111 : Job((111, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.YAHOO_CONTACTS})),
    112 : Job((112, "contacts.tasks.close_linkedin_contacts_account", 0, atp_const.JOB_ETA_TYPE_NEVER, {"linkedin_id": 0})),
    113 : Job((113, "contacts.tasks.reactivate_linkedin_contacts_account", 0, atp_const.JOB_ETA_TYPE_NEVER, {"linkedin_id": 0})),
    114 : Job((114, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.IPHONE})),
    115 : Job((115, "contacts.tasks.sync_email_messages", 43200, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.YAHOO_EMAIL}), throttleable=True, external_apis=[const.YAHOO_EMAIL]),
    116 : Job((116, "contacts.tasks.sync_email_messages", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "attempt_incremental": "False", "service": const.YAHOO_EMAIL}), external_apis=[const.YAHOO_EMAIL]),
    117 : Job((117, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.YAHOO_EMAIL})),
    118 : Job((118, "contacts.tasks.sync_calendar_events", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"profile": 0, "service": const.YAHOO_CALENDAR}), throttleable=True, external_apis=[const.YAHOO_CALENDAR]),
    119 : Job((119, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.YAHOO_CALENDAR})),
    120 : Job((120, "contacts.tasks.clean_merged_contact_action_table", 86400, atp_const.JOB_ETA_TYPE_CURRENT_TIME, {"shard_id": 0}), all_users=True),
    121 : Job((121, "contacts.tasks.update_email_address", 0, atp_const.JOB_ETA_TYPE_NEVER, {"linkedin_id": 0})),
    122 : Job((122, "contacts.tasks.migrate_connections", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0})),
    123 : Job((123, "contacts.tasks.migrate_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0})),
    124 : Job((124, "contacts.tasks.update_profile", 0, atp_const.JOB_ETA_TYPE_NEVER, {"linkedin_id": 0})),
    125 : Job((125, "contacts.tasks.update_timestamp", 0, atp_const.JOB_ETA_TYPE_NEVER, {"linkedin_id": 0})),
    126 : Job((126, "contacts.tasks.sync_uploaded_contacts", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.IPHONE})),
    127 : Job((127, "contacts.tasks.remove_associated_data", 0, atp_const.JOB_ETA_TYPE_NEVER, {"profile": 0, "service": const.ADDRESS_BOOK_IMPORT})),
})
